cmake_minimum_required(VERSION 3.14)
project(PR3_3_C)

set(CMAKE_CXX_STANDARD 14)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

add_subdirectory(../PR3_3_C/lib/googletest)

include_directories(/opt/homebrew/opt/ncurses/include)
link_directories(/opt/homebrew/opt/ncurses/lib)

add_executable(PR3_3_C
        classes/Fraction.h
        classes/Fraction.cpp
        classes/Object.h
        classes/Object.cpp
        main.cpp
)

target_link_libraries(PR3_3_C)

add_executable(PR3_3_C_tests
        classes/Fraction.h
        classes/Fraction.cpp
        classes/Object.h
        classes/Object.cpp
        tests/tests.cpp
)

target_link_libraries(PR3_3_C_tests gtest gtest_main)

enable_testing()
include(GoogleTest)
gtest_discover_tests(PR3_3_C_tests)
